import streamlit as st
import requests
import io
from PIL import Image

# --- API KEYS FROM STREAMLIT SECRETS ---
try:
    HF_TOKEN = st.secrets["HF_TOKEN"]
    PIXABAY_KEY = st.secrets["PIXABAY_KEY"]
except Exception:
    st.error("කරුණාකර Streamlit Cloud Settings -> Secrets වල HF_TOKEN සහ PIXABAY_KEY ඇතුළත් කරන්න!")
    st.stop()

# --- UI SETTINGS ---
st.set_page_config(page_title="Alpha AI - Multimedia Elite", page_icon="🚀", layout="centered")

# Custom CSS for Professional Dark UI
st.markdown("""
    <style>
    .main { background-color: #050505; color: white; }
    .stTextInput > div > div > input, .stTextArea textarea { 
        background-color: #111; color: #00ffcc; border: 1.5px solid #00ffcc; border-radius: 10px;
    }
    .stButton>button {
        width: 100%;
        background: linear-gradient(90deg, #00ffcc, #0055ff);
        color: white; font-weight: bold; border-radius: 12px; height: 3.5em; border: none;
        transition: 0.3s;
    }
    .stButton>button:hover { transform: scale(1.02); box-shadow: 0 0 15px rgba(0, 255, 204, 0.4); }
    .result-card {
        border: 1px solid #333; padding: 15px; border-radius: 15px; margin-bottom: 25px;
        background-color: #111; box-shadow: 0 4px 10px rgba(0,0,0,0.3);
    }
    footer {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

st.title("🚀 Alpha AI Multimedia Elite")
st.markdown("### Created by **Hasith Karunarathna**")
st.write("AI මගින් රූප මැවීමට සහ උසස් තත්වයේ වීඩියෝ සෙවීමට ඇති එකම තැන.")

# --- TABS FOR NAVIGATION ---
tab1, tab2 = st.tabs(["🎨 AI Image Generator", "🎥 Real Video Finder"])

# --- TAB 1: AI IMAGE GENERATOR (Hugging Face) ---
with tab1:
    st.header("AI Image Generator")
    img_prompt = st.text_area("ඔබට අවශ්‍ය රූපය ගැන ලියන්න (Prompt):", key="img_p", 
                             placeholder="e.g. A futuristic city in Sri Lanka, cinematic lighting, 8k...")
    
    if st.button("Generate AI Image ✨"):
        if img_prompt:
            with st.spinner("Alpha AI රූපය නිර්මාණය කරමින් පවතී..."):
                try:
                    API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2-1"
                    headers = {"Authorization": f"Bearer {HF_TOKEN}"}
                    response = requests.post(API_URL, headers=headers, json={"inputs": img_prompt}, timeout=120)
                    
                    if response.status_code == 200:
                        image_bytes = response.content
                        image = Image.open(io.BytesIO(image_bytes))
                        st.image(image, use_container_width=True, caption="Generated by Alpha AI")
                        st.download_button("Download Image 📥", image_bytes, "alpha_ai_image.png", "image/png")
                    elif response.status_code == 503:
                        st.warning("Model එක load වෙමින් පවතී. කරුණාකර තත්පර 15කින් නැවත උත්සාහ කරන්න.")
                    else:
                        st.error(f"Error {response.status_code}: පසුව උත්සාහ කරන්න.")
                except Exception as e:
                    st.error(f"දෝෂයක් සිදු විය: {e}")
        else:
            st.warning("කරුණාකර විස්තරයක් ඇතුළත් කරන්න.")

# --- TAB 2: REAL VIDEO FINDER (Pixabay) ---
with tab2:
    st.header("Real Video Search")
    vid_query = st.text_input("ඔබට අවශ්‍ය වීඩියෝව සොයන්න (Search):", key="vid_q", placeholder="e.g. Nature, Space, Technology...")
    
    if st.button("Search Videos 🔍"):
        if vid_query:
            with st.spinner("Alpha AI දත්ත පද්ධතිය පරීක්ෂා කරමින් පවතී..."):
                try:
                    v_url = f"https://pixabay.com/api/videos/?key={PIXABAY_KEY}&q={vid_query.replace(' ', '+')}&per_page=10"
                    v_res = requests.get(v_url, timeout=30).json()

                    if v_res.get('hits'):
                        for video in v_res['hits']:
                            st.markdown('<div class="result-card">', unsafe_allow_html=True)
                            
                            # වීඩියෝ ලින්ක් එක ලබා ගැනීම
                            v_link = video['videos']['medium']['url']
                            st.video(v_link)
                            
                            # Resolution දත්ත ලබා ගැනීම (KeyError මගහැරීමට .get පාවිච්චි කර ඇත)
                            v_data = video['videos']['medium']
                            width = v_data.get('width', 'N/A')
                            height = v_data.get('height', 'N/A')
                            
                            st.write(f"🎞️ Resolution: {width}x{height}")
                            st.markdown(f'<a href="{v_link}" target="_blank"><button style="width:100%; padding:10px; border-radius:8px; background-color:#28a745; color:white; border:none; cursor:pointer;">Download Video 📥</button></a>', unsafe_allow_html=True)
                            st.markdown('</div>', unsafe_allow_html=True)
                    else:
                        st.warning("ගැළපෙන වීඩියෝ කිසිවක් හමු වූයේ නැත.")
                except Exception as e:
                    st.error(f"දෝෂයක් සිදු විය: {e}")
        else:
            st.warning("කරුණාකර සොයන වචනයක් ඇතුළත් කරන්න.")

st.divider()
st.caption("Alpha AI Elite Edition | Status: Online ✅ | Created by Hasith Karunarathna")
