import streamlit as st
import fal_client
import os

# --- API CONFIGURATION ---
os.environ["FAL_KEY"] = "e17aeca9-b41e-4cac-95f0-996370af31ff:10878663de189655b7340d51c1518534"

# --- UI SETTINGS ---
st.set_page_config(page_title="Alpha AI - Multimodal", page_icon="🎨", layout="centered")

st.title("🎨 Alpha AI Image Generator")
st.subheader("Created by Hasith")
st.write("ඔබට අවශ්‍ය ඕනෑම රූපයක් වචන වලින් නිර්මාණය කරන්න.")

# --- TEXT TO IMAGE SECTION ---
prompt = st.text_area("ඔබේ සිතුවිල්ල මෙතන ලියන්න (Prompt):", placeholder="Example: A futuristic city in Sri Lanka with flying cars, cinematic lighting, 8k")

aspect_ratio = st.selectbox("රූපයේ ප්‍රමාණය (Aspect Ratio):", ["1:1", "16:9", "9:16"])

if st.button("Generate Image ✨"):
    if prompt:
        with st.spinner("Fal.ai Cloud හරහා රූපය නිර්මාණය කරමින් පවතී..."):
            try:
                # Flux.1 [dev] model එක භාවිතා කිරීම (ඉතාමත් උසස් තත්වයේ රූප සඳහා)
                handler = fal_client.submit(
                    "fal-ai/flux/dev",
                    arguments={
                        "prompt": prompt,
                        "image_size": "landscape_16_9" if aspect_ratio == "16:9" else "square" if aspect_ratio == "1:1" else "portrait_4_3",
                        "num_inference_steps": 28,
                        "guidance_scale": 3.5
                    },
                )
                
                result = handler.get()
                image_url = result['images'][0]['url']
                
                if image_url:
                    st.success("රූපය සාර්ථකව නිර්මාණය කළා!")
                    st.image(image_url, caption=f"Generated by Alpha AI: {prompt}")
                    
                    # රූපය Download කරගැනීමට
                    st.markdown(f'<a href="{image_url}" download="alpha_ai_image.png">Download Image 📥</a>', unsafe_allow_html=True)
                
            except Exception as e:
                st.error(f"දෝෂයක් සිදු විය: {str(e)}")
    else:
        st.warning("කරුණාකර මොකක් හරි විස්තරයක් (Prompt) ඇතුළත් කරන්න.")

st.divider()
st.caption("© 2026 Alpha AI | Fast Image Generation Mode")
